declare type LeagueURL = string;
declare type TeamURL = string;

declare type LeagueName = 'PREMIER_LEAGUE' | 'LA_LIGA' | 'SERIE_A' | 'BUNDESLIGA' | 'LIGUE_1' | 'SUPER_LIG' | 'EREDIVISIE'
    | 'PRIMEIRA_LIGA' | 'SCOTTISH_PREMIERSHIP' | 'JUPILER_PRO_LEAGUE' | 'AUSTRIAN_BUNDESLIGA' | 'UKRAINIAN_PREMIER_LEAGUE'
    | 'RUSSIAN_PREMIER_LEAGUE' | 'SUPER_LEAGUE_GREECE' | 'SUPER_LEAGUE_SWITZERLAND' | 'CROATIAN_FIRST_FOOTBALL_LEAGUE'
    | 'POLISH_EKSTRAKLASA' | 'DANISH_SUPERLIGA' | 'CZECH_FIRST_LEAGUE' | 'ELITESERIEN' | 'ALLSVENSKAN' | 'LIGAT_HAAL'
    | 'NEMZETI_BAJNOKSAG' | 'EFBET_LIGA';
